# This workflow installs the latest version of Terraform CLI and configures the Terraform CLI configuration file
# with an API token for Terraform Cloud (app.terraform.io). On pull request events, this workflow will run
# `terraform init`, `terraform fmt`, and `terraform plan` (speculative plan via Terraform Cloud). On push events
# to the main branch, `terraform apply` will be executed.
#
# Documentation for `hashicorp/setup-terraform` is located here: https://github.com/hashicorp/setup-terraform
#
# To use this workflow, you will need to complete the following setup steps.
#
# 1. Create a `main.tf` file in the root of this repository with the `remote` backend and one or more resources defined.
#   Example `main.tf`:
#     # The configuration for the `remote` backend.
#     terraform {
#       backend "remote" {
#         # The name of your Terraform Cloud organization.
#         organization = "example-organization"
#
#         # The name of the Terraform Cloud workspace to store Terraform state files in.
#         workspaces {
#           name = "example-workspace"
#         }
#       }
#     }
#
#     # An example resource that does nothing.
#     resource "null_resource" "example" {
#       triggers = {
#         value = "A example resource that does nothing!"
#       }
#     }
#
#
# 2. Generate a Terraform Cloud user API token and store it as a GitHub secret (e.g. TF_API_TOKEN) on this repository.
#   Documentation:
#     - https://www.terraform.io/docs/cloud/users-teams-organizations/api-tokens.html
#     - https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
#
# 3. Reference the GitHub secret in step using the `hashicorp/setup-terraform` GitHub Action.
#   Example:
#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v1
#       with:
#         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

name: 'Terraform'

on:
  push:
    tags:
    - '**beta**'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
#       with:
#         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      working-directory: ./terraform
      run: terraform fmt -check

    - name: Region
      working-directory: ./terraform
      run: |
        echo "CI_REPOSITORY_SLUG=$CI_REPOSITORY_SLUG"
        echo "CI_REPOSITORY_OWNER=$CI_REPOSITORY_OWNER"
        echo "CI_REPOSITORY_OWNER_SLUG=$CI_REPOSITORY_OWNER_SLUG"
        echo "CI_REPOSITORY_NAME=$CI_REPOSITORY_NAME"
        echo "CI_REPOSITORY_NAME_SLUG=$CI_REPOSITORY_NAME_SLUG"
        echo "CI_REPOSITORY=$CI_REPOSITORY"
        echo "CI_REF_SLUG=$CI_REF_SLUG"
        echo "CI_ACTION_REF_NAME=$CI_ACTION_REF_NAME"
        echo "CI_ACTION_REF_NAME_SLUG=$CI_ACTION_REF_NAME_SLUG"
        echo "CI_REF_NAME=$CI_REF_NAME"
        echo "CI_REF_NAME_SLUG=$CI_REF_NAME_SLUG"
        echo "CI_REF=$CI_REF"
        echo "CI_HEAD_REF_SLUG=$CI_HEAD_REF_SLUG"
        echo "CI_HEAD_REF=$CI_HEAD_REF"
        echo "CI_BASE_REF_SLUG=$CI_BASE_REF_SLUG"
        echo "CI_BASE_REF=$CI_BASE_REF"
        echo "CI_SHA_SHORT=$CI_SHA_SHORT"
        echo "CI_SHA=$CI_SHA"
        echo "CI_ACTOR=$CI_ACTOR"
        echo "CI_EVENT_NAME=$CI_EVENT_NAME"
        echo "CI_RUN_ID=$CI_RUN_ID"
        echo "CI_RUN_NUMBER=$CI_RUN_NUMBER"
        echo "CI_WORKFLOW=$CI_WORKFLOW"
        echo "CI_ACTION=$CI_ACTION"
        echo "AWS_DEFAULT_REGION"

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      working-directory: ./terraform
      run: terraform plan -var='subdomain=hello123'

      # On push to main, build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
#     - name: Terraform Apply
#       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#       run: terraform apply -auto-approve
